version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./.babelrc:/app/.babelrc
      - ./webpack:/app/webpack
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://localhost:8000
