export { LoginPage } from './account/login';
export { RegistrationPage } from './account/registration';
export { ActivateAccountPage } from './account/activate';
export { SocialAuthPage, SocialAuthErrorPage } from './account/social-auth';
export { HomePage } from './home';
export { MainPage } from './main';
export { AccountPage } from './account';
export { SearchPage } from './search';
export { MyRidesPage } from './my-rides';
export { YourProfilePage } from './profile/your-profile';
export { UserProfilePage } from './profile/user-profile';
export { NewRidePage } from './new-ride';
export { CalendarPage } from './calendar';
export { AddCarPage } from './add-car';
export { RideDetailsPage } from './ride-details';
